### ISSUE TITLE
Image registration

### ISSUE THREAD

**Issue by jtasnimj** [WHUQZhang/PSTCR#1]
Hi,
 for training a model, you require a lot of temporal images. Often they have registration error. Can i know how did you deal with registration error? did you train the model with misaligned training images? or somehow aligned them?if so how did you do it?

**Comment by qzhang95** [comment]
Many thanks for your attention to our works. You can use arcgis or envi tools，to crap the temporal data with the same coordinate system(such as WGS 84) and longitude/latitude.

**Comment by jtasnimj** [comment]
Thanks for your reply.
